Si usted está viendo esto, significa que Juan Eduardo hizo el commit …
nestorsgarzonc/oyt-diner pull request #2
Opened 2022-09-03 02:58 UTC by jubedoyat

…correctamente y el login ya está hecho. De lo contrario, téngale paciencia al susodicho

2022-09-03 13:31 UTC, nestorsgarzonc requested changes
Revisa los comentarios incode

2022-09-03 13:31 UTC, nestorsgarzonc commented on lib/core/router/router.dart
> -    initialLocation: OnBoarding.route,
Deja la ruta inicial el onBoarding, esto solo hazlo con findes de desarrollo

2022-09-03 13:31 UTC, nestorsgarzonc commented on lib/ui/auth/login_screen.dart
> +          Form(
Usa los Key para hacer la validacion, mira esto https://docs.flutter.dev/cookbook/forms/validation

2022-09-03 13:31 UTC, nestorsgarzonc commented on lib/ui/auth/login_screen.dart
> +                CustomTextField(label: 'Correo'),
Agregale a cada CustomTextField el TextEditingController

2022-09-03 13:31 UTC, nestorsgarzonc commented on lib/ui/auth/login_screen.dart
> +            onPressed: () {},
Crea una funcion para manejar la logica de cuando se presione el boton

2022-09-04 04:24 UTC, jubedoyat commented on lib/core/router/router.dart
> -    initialLocation: OnBoarding.route,
Ya estaba hecho, pero no sé por qué no salió xd

2022-09-04 04:25 UTC, jubedoyat commented on lib/ui/auth/login_screen.dart
> +                CustomTextField(label: 'Correo'),
Hecho.

2022-09-07 16:54 UTC, nestorsgarzonc requested changes

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/core/router/router.dart
> +    initialLocation: productDetail.route,
Las clases deben iniciar en mayúsculas

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/core/router/router.dart
> +        builder: (context, state) => const productDetail(),
Las clases deben iniciar en mayúscula

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/core/validators/text_form_validator.dart
> +      return 'Por favor, ingrese un texto';
En vez de decir un texto di que contraseña

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/core/validators/text_form_validator.dart
> +      return 'Por favor, ingrese un texto';
Usa una expresión regular para validar el correo

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/Product/product_detail.dart
> +// ignore_for_file: non_constant_identifier_names
Los ignore son malas prácticas, quítalo

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/Product/product_detail.dart
> +// ignore: camel_case_types
Los ignore son malas prácticas, quítalo

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/auth/login_screen.dart
> +            onPressed: (){},
Te falta la lógica del registro como lo hablamos

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/Product/product_detail.dart
> +int FoodQuantity = 0;
No uses variables globales

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/Product/product_detail.dart
> +// ignore: camel_case_types
Los ignore es una mala práctica

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/Product/product_detail.dart
> +void AddToFoodQuantity(){
Las funciones inician en minúsculas

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/Product/product_detail.dart
> +void RemoveFromFoodQuantity(){
Las funciones inician en minúsculas

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/Product/product_detail.dart
> +  FoodQuantity--;
Acá tendrías que hacer un setState, esta noche les explico

2022-09-07 16:54 UTC, nestorsgarzonc commented on lib/ui/Product/product_detail.dart
> +int FoodQuantity = 0;
Eso tiene que ir en el widget

2022-09-12 22:25 UTC, nestorsgarzonc approved these changes

2022-09-12 22:26 UTC, merged